openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /tasks/update:
    post:
      tags:
      - task-controller
      operationId: update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tasks'
      responses:
        200:
          description: default response
          content:
            '*/*':
              schema:
                type: string
  /tasks/count:
    get:
      tags:
      - task-controller
      operationId: count
      responses:
        200:
          description: default response
          content:
            '*/*':
              schema:
                type: integer
                format: int64
  /tasks/delete/{id}:
    get:
      tags:
      - task-controller
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: default response
  /tasks/insert:
    post:
      tags:
      - task-controller
      operationId: insert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tasks'
      responses:
        201:
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/tasks'
  /tasks/{id}:
    get:
      tags:
      - task-controller
      operationId: searchById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/tasks'
  /tasks:
    get:
      tags:
      - task-controller
      operationId: allTasks
      responses:
        200:
          description: default response
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tasks'
components:
  schemas:
    tasks:
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
        status:
          type: string
